version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQLHOST=db:3306
      - MYSQLDATABASE=math_cs_platform
      - MYSQLUSER=root
      - MYSQLPASSWORD=Password123.
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Password123.
      MYSQL_DATABASE: math_cs_platform
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/1.sql
      - ./exam_tables.sql:/docker-entrypoint-initdb.d/2.sql

volumes:
  db_data: