<?php
// =============================================
// config/lang.php - نظام تبديل اللغة (عربي/إنجليزي)
// يُستدعى في أول كل صفحة بعد config/session.php مباشرة
// =============================================

$currentLang = $_COOKIE['site_lang'] ?? 'ar';
if (!in_array($currentLang, ['ar', 'en'], true)) {
    $currentLang = 'ar';
}
$currentDir = ($currentLang === 'ar') ? 'rtl' : 'ltr';

$TRANSLATIONS = [
    'ar' => [
        // ===== عام / نافيجيشن =====
        'brand'              => 'المنصة الذكية - كلية العلوم',
        'nav_home'           => 'الرئيسية',
        'nav_features'       => 'المميزات',
        'nav_sections'       => 'الأقسام',
        'nav_feedback'       => 'شاركنا',
        'nav_login'          => 'تسجيل الدخول',
        'nav_register'       => 'إنشاء حساب',
        'nav_logout'         => 'تسجيل الخروج',
        'lang_toggle'        => 'English',

        // ===== لوحة التحكم (index.php) =====
        'dash_content'       => 'المحتوى التعليمي',
        'dash_schedule'      => 'الجدول الدراسي',
        'dash_exams_sched'   => 'جدول الامتحانات',
        'dash_online_exams'  => 'الامتحانات الإلكترونية',
        'dash_pending'       => 'ملفات قيد المراجعة',
        'dash_profile'       => 'الملف الشخصي',

        // ===== صفحة الدكتور =====
        'doctor_upload_title'=> 'رفع المحتوى التعليمي',
        'doctor_sidebar_item'=> 'رفع المحتوى',

        // ===== يمين الفورم (لوحة المميزات المشتركة) =====
        'auth_brand_title'      => 'المنصة الذكية لكلية العلوم',
        'auth_features_lecture' => 'المحاضرات الخاصة بكل مادة',
        'auth_features_tasks'   => 'نظام المهام التفاعلية',
        'auth_features_section' => 'السكاشن',
        'auth_features_task2'   => 'التاسكات',
        'auth_features_exams'   => 'امتحانات إلكترونية متكاملة',

        // ===== تسجيل الدخول =====
        'login_title'        => 'تسجيل الدخول',
        'login_subtitle'     => 'أدخل بيانات حسابك للوصول إلى المنصة',
        'login_welcome_back' => 'مرحباً بعودتك!',
        'login_welcome_desc' => 'سجل دخولك للوصول الى المنصة الذكية المتكاملة لكلية العلوم شعبة الرياضيات وعلوم الحاسب جامعة السويس',
        'login_role_label'   => 'نوع الحساب',
        'login_role_student' => 'طالب',
        'login_role_doctor'  => 'دكتور',
        'login_code_label'       => 'الكود الجامعي',
        'login_code_placeholder' => 'ادخل الكود الجامعي الخاص بك',
        'login_code_hint'        => 'استخدم الكود الجامعي الرسمي الخاص بك',
        'login_code_error'       => 'من فضلك اكتب الكود الجامعي',
        'login_email_label'       => 'الايميل الجامعي',
        'login_email_placeholder' => 'ادخل البريد الجامعي الخاص بك',
        'login_email_hint'        => 'استخدم البريد الجامعي الرسمي المسجل لدى الإدارة',
        'login_email_error'       => 'من فضلك اكتب الايميل الجامعي',
        'login_password_label'       => 'كلمة المرور',
        'login_password_placeholder' => 'أدخل كلمة المرور',
        'login_password_error'       => 'من فضلك اكتب كلمة المرور',
        'login_show'          => 'إظهار',
        'login_hide'          => 'إخفاء',
        'login_remember'      => 'تذكرني على هذا الجهاز',
        'login_forgot'        => 'نسيت كلمة المرور؟',
        'login_submit'        => 'تسجيل الدخول',
        'login_submitting'    => 'جاري تسجيل الدخول...',
        'login_or'            => 'أو',
        'login_no_account'    => 'ليس لديك حساب؟',
        'login_create_link'   => 'أنشئ حساب جديد',
        'login_role_note'     => 'الدور (طالب/ادمن) يتم تحديده من قِبَل الأدمن',
        'login_toast_fill'    => 'راجع البيانات أولاً',
        'login_toast_success' => '✅ تم تسجيل الدخول بنجاح، جاري التحويل...',
        'login_toast_error'   => 'حدث خطأ، حاول مرة أخرى',
        'login_toast_conn_error' => 'خطأ في الاتصال بالخادم، حاول مرة أخرى',

        // ===== رسائل auth/login.php =====
        'srv_login_fill_fields'    => 'الرجاء إدخال الكود الجامعي وكلمة المرور',
        'srv_login_wrong_creds'    => 'الكود الجامعي أو كلمة المرور غير صحيحة',
        'srv_login_success'        => 'تم تسجيل الدخول بنجاح',
        'srv_role_admin'           => 'أدمن',
        'srv_role_doctor'          => 'دكتور',
        'srv_role_student'         => 'طالب',

        // ===== إنشاء حساب =====
        'register_title'      => 'إنشاء حساب',
        'register_subtitle'   => 'أدخل بياناتك لإنشاء حساب جديد على المنصة',
        'register_join_title' => 'انضم إلينا!',
        'register_join_desc'  => 'أنشئ حسابك الآن وانضم إلى المنصة الذكية المتكاملة لكلية العلوم شعبة الرياضيات وعلوم الحاسب جامعة السويس',
        'register_name_label'       => 'الاسم الكامل',
        'register_name_placeholder' => 'أدخل اسمك الكامل',
        'register_name_error'       => 'من فضلك اكتب اسمك الكامل',
        'register_code_label'       => 'الكود الجامعي',
        'register_code_placeholder' => 'أدخل الكود الجامعي الخاص بك',
        'register_code_hint'        => 'استخدم الكود الجامعي الرسمي الخاص بك',
        'register_code_error'       => 'من فضلك اكتب الكود الجامعي',
        'register_grade_label'   => 'الفرقة',
        'register_grade_default' => 'اختر فرقتك الدراسية',
        'register_grade_1'       => 'الفرقة الأولى',
        'register_grade_2'       => 'الفرقة الثانية',
        'register_grade_3'       => 'الفرقة الثالثة',
        'register_grade_4'       => 'الفرقة الرابعة',
        'register_grade_error'   => 'من فضلك اختر الفرقة',
        'register_password_label'       => 'كلمة المرور',
        'register_password_placeholder' => 'أدخل كلمة المرور (6 أحرف على الأقل)',
        'register_password_error'       => 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
        'register_confirm_label'        => 'تأكيد كلمة المرور',
        'register_confirm_placeholder'  => 'أعد إدخال كلمة المرور',
        'register_confirm_error'        => 'كلمتا المرور غير متطابقتين',
        'register_show'       => 'إظهار',
        'register_hide'       => 'إخفاء',
        'register_submit'     => 'إنشاء الحساب',
        'register_submitting' => 'جاري إنشاء الحساب...',
        'register_or'         => 'أو',
        'register_have_account' => 'لديك حساب بالفعل؟',
        'register_login_link'   => 'تسجيل الدخول',
        'register_role_note'    => 'الدور (طالب/ادمن) يتم تحديده من قِبَل الأدمن',
        'register_toast_fill'      => 'راجع البيانات أولاً',
        'register_toast_success'   => '✅ تم إنشاء الحساب بنجاح، جاري التحويل...',
        'register_toast_error'     => 'حدث خطأ، حاول مرة أخرى',
        'register_toast_conn_error'=> 'خطأ في الاتصال بالخادم، حاول مرة أخرى',

        // ===== رسائل auth/register.php =====
        'srv_reg_fill_fields'   => 'الرجاء إكمال جميع الحقول',
        'srv_reg_pass_mismatch' => 'كلمتا المرور غير متطابقتين',
        'srv_reg_pass_short'    => 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
        'srv_reg_code_taken'    => 'هذا الكود الجامعي مسجل بالفعل',
        'srv_reg_success'       => 'تم إنشاء الحساب بنجاح',

        // ===== الملف الشخصي =====
        'profile_faculty'       => 'كلية العلوم',
        'profile_academic_data' => 'البيانات الأكاديمية',
        'profile_code'          => 'الكود الجامعي',
        'profile_full_name'     => 'الاسم الكامل',
        'profile_grade'         => 'الفرقة',
        'profile_dept'          => 'القسم',
        'profile_role'          => 'الدور',
        'profile_email'         => 'الإيميل الجامعي',
        'profile_personal_email'=> 'الإيميل الشخصي',
        'profile_degree'        => 'الدرجة العلمية',
        'profile_join_year'     => 'سنة الالتحاق',
        'profile_experience'    => 'الخبرة',
        'profile_dept_default'  => 'رياضيات وعلوم الحاسب',
        'grade_1' => 'الفرقة الأولى', 'grade_2' => 'الفرقة الثانية',
        'grade_3' => 'الفرقة الثالثة', 'grade_4' => 'الفرقة الرابعة',

        // ===== شاركنا (JS) =====
        'contact_topic_none'    => 'غير محدد',
        'contact_sending'       => 'جاري الإرسال...',
        'contact_error'         => 'حدث خطأ، حاول مرة أخرى',
        'contact_conn_error'    => '⚠️ تعذر الاتصال بالخادم',
        'contact_submit_btn'    => 'إرسال رأيك',

        // ===== مودال الرفع =====
        'upload_modal_title'    => 'رفع ملف جديد',
        'upload_choose_file_err'=> '⚠️ اختر ملفاً للرفع',
        'upload_no_subject_err' => '⚠️ خطأ: لا يوجد مادة محددة',
        'upload_uploading'      => 'جاري الرفع...',
        'upload_conn_error'     => '⚠️ خطأ في الاتصال بالخادم',
        'upload_submit_btn'     => 'رفع الملف',
        'upload_preview_title'  => 'معاينة الملف',
        'upload_no_preview'     => 'لا يمكن معاينة هذا النوع من الملفات مباشرةً',
        'upload_download_file'  => 'تحميل الملف ⬇',
        'upload_video_unsupported' => 'المتصفح لا يدعم تشغيل الفيديو.',

        // ===== كروت الملفات =====
        'file_loading_subjects' => 'جاري تحميل المواد...',
        'file_no_subjects_term' => 'لا توجد مواد لهذا الترم',
        'file_select_subject_title' => 'اختر مادة لعرض محتواها',
        'file_select_subject_sub'   => 'اختر مادة من القائمة أعلاه ثم اختر نوع المحتوى',
        'file_loading'          => 'جاري التحميل...',
        'file_no_files_title'   => 'لا يوجد ملفات',
        'file_no_files_sub'     => 'لا يوجد محتوى في هذا القسم حتى الآن',
        'file_default_name'     => 'ملف',
        'file_view_btn'         => 'عرض',
        'file_download_btn'     => 'تحميل',
        'file_delete_btn'       => 'حذف',
        'file_approve_btn'      => '✅ قبول',
        'file_reject_btn'       => '❌ رفض',
        'file_uploaded_by'      => 'رُفع بواسطة',
        'file_section_label'    => 'سكشن',
        'file_select_subject_first' => 'اختر مادة أولاً',
        'status_approved'       => '✅ منشور',
        'status_pending'        => '⏳ قيد المراجعة',
        'status_rejected'       => '❌ مرفوض',
        'type_lecture'          => 'محاضرة',
        'type_task'             => 'تاسك',
        'type_assignment'       => 'اسايمنت',
        'type_section'          => 'سكشن',
        'type_schedule'         => 'جدول',
        'type_exam_schedule'    => 'جدول امتحانات',

        // ===== إضافات: الترم / زرار التحديث / عرض الفرقة =====
        'semester_label'        => 'الترم:',
        'semester_1'            => 'الترم الأول',
        'semester_2'            => 'الترم الثاني',
        'dash_refresh_btn'      => 'تحديث المحتوى',
        'dash_view_grade'       => 'عرض الفرقة:',

        // ===== الصفحة الرئيسية (Home) =====
        'home_title_highlight' => 'المنصة الذكية المتكاملة',
        'home_title_rest'      => 'لكلية العلوم شعبة الرياضيات وعلوم الحاسب',
        'home_subtitle'        => 'المنصة الذكية هي منصة متكاملة تجمع بين المحاضرات والمهام التفاعلية والسكاشن والامتحانات الإلكترونية في مكان واحد.',
        'home_cta'             => 'ابدأ التعلم الآن',
        'home_badge_lectures'  => 'محاضرات',
        'home_badge_sections'  => 'سكاشن',
        'home_badge_tasks'     => 'مهام',
        'home_badge_exams'     => 'امتحانات',
        'home_cta_arrow'       => '←',

        // ===== صفحة المميزات =====
        'feat_title'    => 'مميزات المنصة',
        'feat_subtitle' => 'كل ما تحتاجه للتعلم الإلكتروني في مكان واحد',
        'feat1_title'   => 'منصة ذكية متكاملة',
        'feat1_desc'    => 'بيئة تعليمية شاملة تجمع كل ما يحتاجه الطالب والمحاضر في مكان واحد ذكي، مصمّم لتحقيق أعلى كفاءة تعليمية ممكنة',
        'feat2_title'   => 'محاضراتك وسكاشنك في مكان واحد',
        'feat2_desc'    => 'وصول فوري لجميع المحاضرات المسجلة والسكاشن في أي وقت ومن أي مكان',
        'feat3_title'   => 'تسجيل دخول طلاب وأدمن سلس',
        'feat3_desc'    => 'نظام تسجيل دخول مرن وآمن يدعم الطلاب والمشرفين، مع تحديد الأدوار تلقائياً',

        // ===== الجدول الدراسي =====
        'schedule_subtitle'   => 'جدولك الدراسي للفصل الحالي',
        'schedule_pick_sec'   => 'رقم السكشن:',
        'schedule_choose_sec' => 'اختر السكشن',
        'schedule_empty_title'=> 'اختر رقم السكشن لعرض الجدول',
        'schedule_empty_sub'  => 'الفرقة يتم تحديدها تلقائياً من حسابك',
        'schedule_upload_btn' => 'رفع جدول',
        'filter_grade_label'  => 'الفرقة:',

        // ===== بانر تسجيل الدخول المطلوب =====
        'login_required_banner' => 'يجب تسجيل الدخول أولاً للوصول إلى محتوى المنصة',

        // ===== كروت مميزات إضافية =====
        'feat4_title' => 'المهام التفاعلية',
        'feat4_desc'  => 'استلم وسلّم مهامك إلكترونياً مع تتبع فوري للتقدم، وتلقّ تعليقات الأساتذة وتقييماتهم',
        'feat5_title' => 'امتحانات إلكترونية',
        'feat5_desc'  => 'اخضع للامتحانات إلكترونياً بنظام آمن وموثوق مع نتائج فورية وتحليل شامل للأداء',
        'feat6_title' => 'دعم عند مواجهة أي أخطاء',
        'feat6_desc'  => 'فريق دعم فني متكامل جاهز لمساعدتك في حل أي مشكلة أو خطأ تواجهه أثناء الاستخدام',

        // ===== شاركنا (نصوص ثابتة في HTML) =====
        'contact_page_title'   => 'شاركنا برأيك',
        'contact_page_sub'     => 'رأيك يهمنا! ساعدنا في تحسين المنصة وتطويرها لتلبية احتياجاتك بشكل أفضل.',
        'contact_info_email'   => 'البريد الإلكتروني',
        'contact_info_loc'     => 'الموقع',
        'contact_info_loc_val' => 'جامعة السويس – كلية العلوم',
        'contact_info_reply'   => 'وقت الرد',
        'contact_info_reply_val' => 'خلال 24 ساعة من استلام رأيك',
        'contact_info_support' => 'الدعم الفني',
        'contact_info_support_val' => 'فريق متخصص جاهز لمساعدتك دائماً',
        'contact_name_label'   => 'الاسم',
        'contact_name_ph'      => 'أدخل اسمك الكامل',
        'contact_name_err'     => 'يرجى إدخال الاسم الكامل',
        'contact_code_label'   => 'الكود الجامعي',
        'contact_code_ph'      => 'أدخل الكود الجامعي',
        'contact_code_err'     => 'يرجى إدخال الكود الجامعي',
        'contact_email_label'  => 'البريد الإلكتروني',
        'contact_email_ph'     => 'أدخل بريدك الإلكتروني',
        'contact_email_err'    => 'يرجى إدخال بريد إلكتروني صحيح',
        'contact_topic_label'  => 'موضوع الرأي',
        'contact_topic_ui'     => 'واجهة المنصة',
        'contact_topic_content'=> 'المحتوى التعليمي',
        'contact_topic_perf'   => 'الأداء والسرعة',
        'contact_topic_support'=> 'الدعم الفني',
        'contact_topic_suggest'=> 'مقترحات عامة',
        'contact_topic_other'  => 'أخرى',
        'contact_msg_label'    => 'رأيك / اقتراحك',
        'contact_msg_ph'       => 'اكتب رأيك أو اقتراحك هنا...',
        'contact_msg_err'      => 'يرجى كتابة رأيك أو اقتراحك',
        'contact_thanks_title' => 'شكراً لك!',
        'contact_thanks_msg'   => 'تم إرسال رأيك بنجاح. سنأخذه بعين الاعتبار في تطوير المنصة.',
        'contact_close_btn'    => 'إغلاق',

        // ===== سايدبار: اسم مختصر =====
        'sidebar_brand_short'  => 'المنصة الذكية',

        // ===== أزرار نوع المحتوى =====
        'content_lectures' => 'المحاضرات',
        'content_tasks'    => 'التاسكات',
        'content_assign'   => 'الاسايمنتات',
        'content_sections' => 'السكاشن',

        // ===== فلتر السكشن + رفع ملف =====
        'section_all'        => 'الكل',
        'upload_btn_generic' => 'رفع ملف',

        // ===== جدول الامتحانات =====
        'exam_sched_subtitle'  => 'مواعيد الامتحانات',
        'exam_sched_upload'    => 'رفع جدول امتحانات',
        'view_grade_label'     => 'عرض فرقة:',
        'exam_sched_loading'   => 'جاري تحميل جدول الامتحانات...',
        'exam_sched_auto'      => 'يتم تحديده تلقائياً حسب فرقتك',

        // ===== الامتحانات الإلكترونية =====
        'online_exams_admin_title'  => 'إدارة الامتحانات الإلكترونية',
        'online_exams_title'        => 'الامتحانات الإلكترونية',
        'online_exams_admin_sub'    => 'رفع الامتحانات ومراجعة إجابات الطلاب',
        'online_exams_sub'          => 'أداء الامتحانات الإلكترونية وعرض نتائجك',
        'create_exam_btn'           => '+ إنشاء امتحان',
        'exam_basic_data'           => '📝 بيانات الامتحان الأساسية',
        'exam_grade_label'          => 'الفرقة *',
        'exam_subject_label'        => 'المادة *',
        'exam_choose_subject'       => 'اختر المادة...',
        'exam_title_label'          => 'عنوان الامتحان *',
        'exam_title_ph'             => 'مثال: امتحان الإحصاء - الفصل الأول',
        'exam_desc_label'           => 'الوصف (نوع الامتحان)',
        'exam_desc_ph'              => 'مثال: امتحان MCQ يشمل الفصول 1-5 / امتحان مقالي...',
        'exam_duration_label'       => 'مدة الامتحان (دقيقة) *',
        'exam_total_grade_label'    => 'الدرجة الكلية *',
        'exam_pass_grade_label'     => 'درجة النجاح *',
        'exam_questions_title'      => '❓ الأسئلة',
        'exam_add_question_btn'     => 'إضافة سؤال',
        'exam_upload_btn'           => 'رفع الامتحان',
        'exam_cancel_btn'           => 'إلغاء',
        'exam_tab_list'             => 'قائمة الامتحانات',
        'exam_tab_submissions'      => 'مراجعة الإجابات',
        'exam_tab_available'        => 'الامتحانات المتاحة',
        'exam_tab_results'          => 'نتائجي',
        'exam_loading'              => 'جاري تحميل الامتحانات...',

        // ===== لوحة المراجعة =====
        'pending_sub'      => 'الملفات المرفوعة من الطلاب وتنتظر موافقتك',
        'pending_refresh'  => 'تحديث',
        'pending_loading'  => 'جاري التحميل...',

        // ===== الملف الشخصي (نصوص ثابتة احتياطية) =====
        'profile_static_sub'   => 'معلوماتك الشخصية والأكاديمية',
        'profile_static_dept'  => 'رياضيات وعلوم الحاسب · كلية العلوم',
        'profile_section_label'=> 'الشعبة',
        'profile_uni_label'    => 'الجامعة',
        'profile_uni_value'    => 'جامعة السويس',

        // ===== مودال الرفع (حقول إضافية) =====
        'modal_grade_label'      => 'الفرقة',
        'modal_section_label'    => 'رقم السكشن',
        'modal_choose_file_label'=> 'اختر الملف',
        'modal_choose_file_text' => 'اضغط لاختيار ملف من جهازك',
        'modal_choose_file_short'=> 'اضغط لاختيار ملف',
        'modal_upload_btn'       => 'رفع الملف',
        'modal_cancel_btn'       => 'إلغاء',

        // ===== تأكيد الحذف =====
        'delete_confirm_title' => 'حذف الملف',
        'delete_confirm_msg'   => 'هل أنت متأكد من حذف هذا الملف نهائياً؟<br>لا يمكن التراجع عن هذا الإجراء.',
        'delete_confirm_yes'   => 'حذف',
        'delete_confirm_no'    => 'إلغاء',
        'select_placeholder'   => 'اختر...',

        // ===== جدول الامتحانات (JS) =====
        'exam_sched_empty_title' => 'لا يوجد جدول امتحانات',
        'exam_sched_empty_sub'   => 'لم يتم رفع جدول الامتحانات بعد',
        'exam_sched_card_type'   => 'جدول امتحانات',
        'exam_sched_load_err'    => 'خطأ في تحميل جدول الامتحانات',

        // ===== لوحة المراجعة (JS) =====
        'pending_empty_title' => 'لا توجد ملفات قيد المراجعة',
        'pending_empty_sub'   => 'جميع الملفات تمت مراجعتها',
        'pending_load_err'    => 'خطأ في تحميل الملفات',

        // ===== قائمة الامتحانات =====
        'exam_load_err'          => 'خطأ في تحميل الامتحانات',
        'exam_none_for_grade'    => 'لا توجد امتحانات لهذه الفرقة',
        'exam_none_available'    => 'لا توجد امتحانات متاحة حالياً',
        'exam_click'             => 'اضغط',
        'exam_click_to_add'      => 'لإضافة امتحان جديد',
        'exam_will_appear'       => 'ستجد الامتحانات هنا عند إتاحتها من الأدمن',
        'exam_conn_error'        => 'خطأ في الاتصال بالخادم',
        'exam_status_active'     => 'مفعّل ✅',
        'exam_status_inactive'   => 'معطّل ⛔',
        'exam_disable_btn'       => '⛔ تعطيل',
        'exam_enable_btn'        => '✅ تفعيل',
        'exam_status_banned'     => 'محظور 🚫',
        'exam_banned_btn'        => 'محظور من الامتحان',
        'exam_status_done'       => 'تم الأداء ✅',
        'exam_submitted_btn'     => 'تم التسليم',
        'exam_status_available'  => 'متاح 🟢',
        'exam_delete_confirm'    => 'هل أنت متأكد من حذف هذا الامتحان وجميع بيانات الطلاب؟',
        'exam_delete_err'        => 'خطأ في الحذف',
        'exam_conn_err_short'    => 'خطأ في الاتصال',
        'exam_generic_err'       => 'خطأ',

        // ===== مراجعة الإجابات =====
        'submissions_loading'    => 'جاري تحميل الإجابات...',
        'submissions_empty_title'=> 'لا توجد امتحانات مسلّمة',
        'submissions_empty_sub'  => 'ستظهر هنا بعد تسليم الطلاب لامتحاناتهم',
        'submissions_load_err'   => 'خطأ في تحميل البيانات',
        'submissions_cheat'      => '⚠️ محاولات غش',
        'submissions_notes'      => 'ملاحظات (اختياري)',
        'submissions_reviewed'   => '✅ تمت المراجعة',
        'submissions_enter_grade'=> 'أدخل الدرجة أولاً',
        'submissions_save_err'   => 'خطأ في الحفظ',
        'submissions_answers_err'=> 'خطأ في تحميل الإجابات',
        'submissions_no_answer'  => 'لم تُكتب إجابة',
        'submissions_no_answer_warn' => '⚠️ بدون إجابة',

        // ===== نتائجي (الطالب) =====
        'results_loading'      => 'جاري تحميل نتائجك...',
        'results_empty_title'  => 'لا توجد نتائج بعد',
        'results_empty_sub'    => 'ستظهر هنا نتائج الامتحانات بعد مراجعتها من الأدمن',
        'results_pass'         => '✅ ناجح',
        'results_fail'         => '❌ راسب',
        'results_pending'      => '⏳ قيد المراجعة',

        // ===== فورم إنشاء الامتحان (JS) =====
        'exam_form_loading_opt'  => 'جاري التحميل...',
        'exam_form_choose_subj'  => 'اختر المادة...',
        'exam_form_load_err_opt' => 'خطأ في التحميل',
        'exam_form_grade_col'    => 'الدرجة',
        'exam_form_question_ph'  => 'اكتب السؤال هنا...',
        'exam_form_choice_a'     => 'الاختيار أ',
        'exam_form_choice_b'     => 'الاختيار ب',
        'exam_form_choice_c'     => 'الاختيار ج',
        'exam_form_choice_d'     => 'الاختيار د',
        'exam_form_question_num' => 'سؤال',
        'exam_form_err_required' => '⚠️ يرجى ملء جميع الحقول الإلزامية',
        'exam_form_err_qtext'    => '⚠️ يرجى ملء نص جميع الأسئلة',
        'exam_form_err_mcq'      => '⚠️ يجب إضافة الاختيار أ وب على الأقل لكل سؤال MCQ',
        'exam_form_err_min1'     => '⚠️ يجب إضافة سؤال واحد على الأقل',
        'exam_form_uploading'    => 'جاري الرفع...',
        'exam_form_success'      => '✅ تم رفع الامتحان بنجاح!',
        'exam_form_upload_err'   => 'خطأ في الرفع',
        'exam_form_conn_err'     => '⚠️ خطأ في الاتصال بالخادم',
        'file_subject_label'     => 'المادة',
        'file_type_label'        => 'النوع',
        'exam_students_submitted'=> '📥 الطلاب الذين سلّموا',
        'exam_student_unit'      => 'طالب',
        'exam_duration_icon'     => '⏱️ المدة',
        'exam_minute_unit'       => 'دقيقة',
        'exam_questions_icon'    => '❓ الأسئلة',
        'exam_question_unit'     => 'سؤال',
        'exam_total_grade_icon'  => '📊 الدرجة الكلية',
        'exam_grade_unit'        => 'درجة',
        'exam_pass_icon'         => '✅ النجاح',
        'exam_start_btn'         => 'ابدأ الامتحان',
        'exam_delete_icon_btn'   => '🗑️ حذف',
        'exam_cheat_prefix'      => '⚠️ محاولات غش',
        'exam_given_grade'       => '✅ الدرجة المُعطاة:',
        'exam_grade_from'        => 'الدرجة (من',
        'exam_save_btn'          => '💾 حفظ',
        'exam_view_answers_btn'  => '🔍 عرض الإجابات',
        'exam_code_prefix'       => '🎓 كود:',
        'exam_enter_grade_first' => 'أدخل الدرجة أولاً',
        'exam_cheat_log_title'   => '⚠️ سجل محاولات الغش',
        'exam_q_prefix'          => 'س',
        'exam_back_to_list'      => 'العودة للقائمة',
        'exam_answers_of'        => 'إجابات:',
        'exam_started_at'        => '⏱️ بدأ:',
        'exam_submitted_at_label'=> '✅ سلّم:',
        'exam_result_of'         => 'من',
        'exam_type_mcq'          => 'اختيار من متعدد (MCQ)',
        'exam_type_essay'        => 'مقالي',
        'exam_marks_ph'          => 'الدرجة',
        'exam_remove_q_btn'      => '✕ حذف',
        'exam_question_text_label' => 'نص السؤال *',
        'exam_correct_answer_label'=> 'الإجابة الصحيحة *',
        'exam_letter_a' => 'أ', 'exam_letter_b' => 'ب', 'exam_letter_c' => 'ج', 'exam_letter_d' => 'د',
        'sched_no_section_title' => 'اختر رقم السكشن لعرض الجدول',
        'sched_no_section_sub'   => 'الفرقة يتم تحديدها تلقائياً من حسابك',
        'sched_empty_title'      => 'لا يوجد جدول لهذا السكشن',
        'sched_empty_sub'        => 'لم يتم رفع الجدول بعد',
        'sched_card_type'        => 'جدول دراسي',
        'sched_load_err'         => 'خطأ في تحميل الجدول',

        // ===== صفحة الدكتور =====
        'doctor_page_title'    => 'لوحة الدكتور - المنصة الذكية - كلية العلوم',
        'doctor_welcome'       => 'مرحباً د.',
        'doc_content_lecture'    => 'المحاضرات',
        'doc_content_assignment' => 'اسيمنت',
        'doc_content_task'       => 'مهام',
        'doc_content_section'    => 'سكاشن',
        'doc_load_subjects_err'  => 'خطأ في تحميل المواد',
        'doc_load_files_err'     => 'خطأ في تحميل الملفات',
        'doc_delete_confirm'     => 'هل أنت متأكد من حذف هذا الملف؟ لا يمكن التراجع عن هذه الخطوة.',
        'doc_delete_failed'      => 'تعذر حذف الملف',
        'doc_conn_error'         => 'خطأ في الاتصال بالخادم',
        'doc_choose_file_first'  => 'اختر ملفاً أولاً',
        'doc_upload_generic_err' => 'حدث خطأ أثناء الرفع',

        // ===== إعادة تعيين كلمة المرور =====
        'reset_page_title'   => 'إعادة تعيين كلمة السر',
        'reset_step_of'      => 'الخطوة %d من 3',

        // خطوة 1
        'reset_s1_title'     => 'إعادة تعيين كلمة السر',
        'reset_s1_sub'       => 'أدخل بياناتك للتحقق من هويتك',
        'reset_s1_code_label'=> 'الكود الجامعي',
        'reset_s1_code_ph'   => 'أدخل الكود الجامعي الخاص بك',
        'reset_s1_code_hint' => 'استخدم الكود الجامعي الرسمي الخاص بك',
        'reset_s1_code_err'  => 'من فضلك أدخل الكود الجامعي',
        'reset_s1_verify_btn'=> 'التحقق من الهوية',
        'reset_s1_remember'  => 'تذكرت كلمة المرور؟',
        'reset_s1_login_link'=> 'تسجيل الدخول',

        // خطوة 2 (OTP)
        'reset_s2_title'     => 'رمز التحقق',
        'reset_s2_sub'       => 'أدخل رمز OTP المرسل عبر الإيميل الخاص بك',
        'reset_s2_label'     => 'رمز التحقق المكون من 6 أرقام',
        'reset_s2_err'       => 'من فضلك أدخل الرمز المكون من 6 أرقام',
        'reset_s2_no_code'   => 'لم يصلك الرمز؟',
        'reset_s2_resend'    => 'إعادة الإرسال',
        'reset_s2_verify_btn'=> 'التحقق من الرمز',
        'reset_s2_back_btn'  => 'العودة للخطوة السابقة',

        // خطوة 3
        'reset_s3_title'      => 'كلمة السر الجديدة',
        'reset_s3_sub'        => 'أدخل كلمة سر جديدة وقوية لحسابك',
        'reset_s3_pass_label' => 'كلمة المرور الجديدة',
        'reset_s3_pass_ph'    => 'أدخل كلمة المرور الجديدة (6 أحرف على الأقل)',
        'reset_s3_pass_err'   => 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
        'reset_s3_confirm_label' => 'تأكيد كلمة المرور الجديدة',
        'reset_s3_confirm_ph' => 'أعد إدخال كلمة المرور الجديدة',
        'reset_s3_confirm_err_empty' => 'من فضلك أكد كلمة المرور',
        'reset_s3_confirm_err_mismatch' => 'كلمتا المرور غير متطابقتين',
        'reset_s3_submit_btn' => 'إعادة تعيين كلمة السر',

        // النجاح
        'reset_success_title' => 'تم بنجاح! 🎉',
        'reset_success_msg'   => 'تم إعادة تعيين كلمة السر الخاصة بك بنجاح.<br>يمكنك الآن تسجيل الدخول بكلمة السر الجديدة.',
        'reset_success_btn'   => 'الذهاب لتسجيل الدخول',

        // اللوحة اليمنى
        'reset_panel_title'   => 'استعادة حسابك',
        'reset_panel_desc'    => 'اتبع الخطوات البسيطة لإعادة تعيين كلمة السر والعودة إلى منصتك الذكية لكلية العلوم شعبة الرياضيات وعلوم الحاسب',
        'reset_prog1'         => 'التحقق من الهوية',
        'reset_prog2'         => 'رمز التحقق',
        'reset_prog3'         => 'كلمة السر الجديدة',
        'reset_feat1'         => 'أمان عالي لحماية حسابك',
        'reset_feat2'         => 'رمز تحقق يُرسل فوراً لإيميلك',
        'reset_feat3'         => 'عملية سريعة وآمنة في 3 خطوات',

        // رسائل JS
        'reset_toast_verifying'   => 'جاري التحقق...',
        'reset_toast_verified'    => 'تم التحقق من الهوية ✓ جاري الانتقال...',
        'reset_toast_wrong_code'  => 'الكود الجامعي غير صحيح',
        'reset_toast_code_notfound'=> 'الكود الجامعي غير موجود',
        'reset_toast_conn_err'    => 'خطأ في الاتصال بالخادم',
        'reset_toast_otp_verified'=> 'تم التحقق من الرمز ✓ جاري الانتقال...',
        'reset_toast_otp_resent'  => 'تم إعادة إرسال رمز التحقق',
        'reset_toast_saving'      => 'جاري الحفظ...',
        'reset_toast_success'     => 'تم إعادة التعيين بنجاح 🎉',
        'reset_toast_generic_err' => 'حدث خطأ، حاول مرة أخرى',
        'reset_show'  => 'إظهار',
        'reset_hide'  => 'إخفاء',
    ],
    'en' => [
        'brand'              => 'Smart Platform - Faculty of Science',
        'nav_home'           => 'Home',
        'nav_features'       => 'Features',
        'nav_sections'       => 'Sections',
        'nav_feedback'       => 'Feedback',
        'nav_login'          => 'Login',
        'nav_register'       => 'Sign Up',
        'nav_logout'         => 'Logout',
        'lang_toggle'        => 'عربي',

        'dash_content'       => 'Educational Content',
        'dash_schedule'      => 'Class Schedule',
        'dash_exams_sched'   => 'Exam Schedule',
        'dash_online_exams'  => 'Online Exams',
        'dash_pending'       => 'Pending Files',
        'dash_profile'       => 'Profile',

        'doctor_upload_title'=> 'Upload Educational Content',
        'doctor_sidebar_item'=> 'Upload Content',

        'auth_brand_title'      => 'Smart Platform - Faculty of Science',
        'auth_features_lecture' => 'Lectures for every subject',
        'auth_features_tasks'   => 'Interactive tasks system',
        'auth_features_section' => 'Sections',
        'auth_features_task2'   => 'Tasks',
        'auth_features_exams'   => 'Fully integrated online exams',

        'login_title'        => 'Login',
        'login_subtitle'     => 'Enter your account details to access the platform',
        'login_welcome_back' => 'Welcome back!',
        'login_welcome_desc' => 'Log in to access the integrated Smart Platform for the Faculty of Science, Math & CS Division, Suez University',
        'login_role_label'   => 'Account Type',
        'login_role_student' => 'Student',
        'login_role_doctor'  => 'Doctor',
        'login_code_label'       => 'University Code',
        'login_code_placeholder' => 'Enter your university code',
        'login_code_hint'        => 'Use your official university code',
        'login_code_error'       => 'Please enter your university code',
        'login_email_label'       => 'University Email',
        'login_email_placeholder' => 'Enter your university email',
        'login_email_hint'        => 'Use your official university email registered with administration',
        'login_email_error'       => 'Please enter your university email',
        'login_password_label'       => 'Password',
        'login_password_placeholder' => 'Enter your password',
        'login_password_error'       => 'Please enter your password',
        'login_show'          => 'Show',
        'login_hide'          => 'Hide',
        'login_remember'      => 'Remember me on this device',
        'login_forgot'        => 'Forgot your password?',
        'login_submit'        => 'Login',
        'login_submitting'    => 'Logging in...',
        'login_or'            => 'or',
        'login_no_account'    => "Don't have an account?",
        'login_create_link'   => 'Create a new account',
        'login_role_note'     => 'The role (student/admin) is set by the admin',
        'login_toast_fill'    => 'Please check your details first',
        'login_toast_success' => '✅ Logged in successfully, redirecting...',
        'login_toast_error'   => 'An error occurred, please try again',
        'login_toast_conn_error' => 'Server connection error, please try again',

        'srv_login_fill_fields'    => 'Please enter your university code and password',
        'srv_login_wrong_creds'    => 'Incorrect university code or password',
        'srv_login_success'        => 'Logged in successfully',
        'srv_role_admin'           => 'Admin',
        'srv_role_doctor'          => 'Doctor',
        'srv_role_student'         => 'Student',

        'register_title'      => 'Create Account',
        'register_subtitle'   => 'Enter your details to create a new account on the platform',
        'register_join_title' => 'Join us!',
        'register_join_desc'  => 'Create your account now and join the integrated Smart Platform for the Faculty of Science, Math & CS Division, Suez University',
        'register_name_label'       => 'Full Name',
        'register_name_placeholder' => 'Enter your full name',
        'register_name_error'       => 'Please enter your full name',
        'register_code_label'       => 'University Code',
        'register_code_placeholder' => 'Enter your university code',
        'register_code_hint'        => 'Use your official university code',
        'register_code_error'       => 'Please enter your university code',
        'register_grade_label'   => 'Grade Level',
        'register_grade_default' => 'Select your grade level',
        'register_grade_1'       => 'First Year',
        'register_grade_2'       => 'Second Year',
        'register_grade_3'       => 'Third Year',
        'register_grade_4'       => 'Fourth Year',
        'register_grade_error'   => 'Please select your grade level',
        'register_password_label'       => 'Password',
        'register_password_placeholder' => 'Enter password (min 6 characters)',
        'register_password_error'       => 'Password must be at least 6 characters',
        'register_confirm_label'        => 'Confirm Password',
        'register_confirm_placeholder'  => 'Re-enter your password',
        'register_confirm_error'        => 'Passwords do not match',
        'register_show'       => 'Show',
        'register_hide'       => 'Hide',
        'register_submit'     => 'Create Account',
        'register_submitting' => 'Creating account...',
        'register_or'         => 'or',
        'register_have_account' => 'Already have an account?',
        'register_login_link'   => 'Login',
        'register_role_note'    => 'The role (student/admin) is set by the admin',
        'register_toast_fill'      => 'Please check your details first',
        'register_toast_success'   => '✅ Account created successfully, redirecting...',
        'register_toast_error'     => 'An error occurred, please try again',
        'register_toast_conn_error'=> 'Server connection error, please try again',

        'srv_reg_fill_fields'   => 'Please fill in all fields',
        'srv_reg_pass_mismatch' => 'Passwords do not match',
        'srv_reg_pass_short'    => 'Password must be at least 6 characters',
        'srv_reg_code_taken'    => 'This university code is already registered',
        'srv_reg_success'       => 'Account created successfully',

        // ===== Profile =====
        'profile_faculty'       => 'Faculty of Science',
        'profile_academic_data' => 'Academic Information',
        'profile_code'          => 'University Code',
        'profile_full_name'     => 'Full Name',
        'profile_grade'         => 'Grade Level',
        'profile_dept'          => 'Department',
        'profile_role'          => 'Role',
        'profile_email'         => 'University Email',
        'profile_personal_email'=> 'Personal Email',
        'profile_degree'        => 'Academic Degree',
        'profile_join_year'     => 'Join Year',
        'profile_experience'    => 'Experience',
        'profile_dept_default'  => 'Math & Computer Science',
        'grade_1' => 'First Year', 'grade_2' => 'Second Year',
        'grade_3' => 'Third Year', 'grade_4' => 'Fourth Year',

        // ===== Feedback (JS) =====
        'contact_topic_none'    => 'Not specified',
        'contact_sending'       => 'Sending...',
        'contact_error'         => 'An error occurred, please try again',
        'contact_conn_error'    => '⚠️ Server connection failed',
        'contact_submit_btn'    => 'Send Feedback',

        // ===== Upload modal =====
        'upload_modal_title'    => 'Upload New File',
        'upload_choose_file_err'=> '⚠️ Please choose a file to upload',
        'upload_no_subject_err' => '⚠️ Error: no subject selected',
        'upload_uploading'      => 'Uploading...',
        'upload_conn_error'     => '⚠️ Server connection error',
        'upload_submit_btn'     => 'Upload File',
        'upload_preview_title'  => 'File Preview',
        'upload_no_preview'     => 'This file type cannot be previewed directly',
        'upload_download_file'  => 'Download File ⬇',
        'upload_video_unsupported' => 'Your browser does not support video playback.',

        // ===== File cards =====
        'file_loading_subjects' => 'Loading subjects...',
        'file_no_subjects_term' => 'No subjects for this semester',
        'file_select_subject_title' => 'Select a subject to view its content',
        'file_select_subject_sub'   => 'Choose a subject above, then select a content type',
        'file_loading'          => 'Loading...',
        'file_no_files_title'   => 'No files',
        'file_no_files_sub'     => 'No content in this section yet',
        'file_default_name'     => 'File',
        'file_view_btn'         => 'View',
        'file_download_btn'     => 'Download',
        'file_delete_btn'       => 'Delete',
        'file_approve_btn'      => '✅ Approve',
        'file_reject_btn'       => '❌ Reject',
        'file_uploaded_by'      => 'Uploaded by',
        'file_section_label'    => 'Section',
        'file_select_subject_first' => 'Please select a subject first',
        'status_approved'       => '✅ Published',
        'status_pending'        => '⏳ Under Review',
        'status_rejected'       => '❌ Rejected',
        'type_lecture'          => 'Lecture',
        'type_task'             => 'Task',
        'type_assignment'       => 'Assignment',
        'type_section'          => 'Section',
        'type_schedule'         => 'Schedule',
        'type_exam_schedule'    => 'Exam Schedule',

        // ===== Additions: Semester / Refresh button / Grade view =====
        'semester_label'        => 'Semester:',
        'semester_1'            => 'First Semester',
        'semester_2'            => 'Second Semester',
        'dash_refresh_btn'      => 'Refresh Content',
        'dash_view_grade'       => 'View Grade:',

        // ===== Home Page (Hero Section) =====
        'home_title_highlight' => 'The Integrated Smart Platform',
        'home_title_rest'      => 'for the Faculty of Science, Math & CS Division',
        'home_subtitle'        => 'The Smart Platform brings lectures, interactive tasks, sections, and online exams together in one place.',
        'home_cta'             => 'Start Learning Now',
        'home_badge_lectures'  => 'Lectures',
        'home_badge_sections'  => 'Sections',
        'home_badge_tasks'     => 'Tasks',
        'home_badge_exams'     => 'Exams',
        'home_cta_arrow'       => '→',

        // ===== Features Page =====
        'feat_title'    => 'Platform Features',
        'feat_subtitle' => 'Everything you need for e-learning in one place',
        'feat1_title'   => 'An Integrated Smart Platform',
        'feat1_desc'    => 'A complete learning environment bringing together everything students and instructors need in one smart place, designed for maximum educational efficiency',
        'feat2_title'   => 'Your Lectures & Sections in One Place',
        'feat2_desc'    => 'Instant access to all recorded lectures and sections, anytime and anywhere',
        'feat3_title'   => 'Seamless Student & Admin Login',
        'feat3_desc'    => 'A flexible, secure login system supporting students and supervisors, with automatic role assignment',

        // ===== Class Schedule =====
        'schedule_subtitle'   => 'Your class schedule for the current semester',
        'schedule_pick_sec'   => 'Section Number:',
        'schedule_choose_sec' => 'Choose Section',
        'schedule_empty_title'=> 'Select a section number to view the schedule',
        'schedule_empty_sub'  => 'Your grade level is determined automatically from your account',
        'schedule_upload_btn' => 'Upload Schedule',
        'filter_grade_label'  => 'Grade:',

        // ===== Login required banner =====
        'login_required_banner' => 'You must log in first to access the platform content',

        // ===== Additional feature cards =====
        'feat4_title' => 'Interactive Tasks',
        'feat4_desc'  => 'Receive and submit your tasks online with instant progress tracking, and get feedback and grades from instructors',
        'feat5_title' => 'Online Exams',
        'feat5_desc'  => 'Take exams online through a secure, reliable system with instant results and comprehensive performance analysis',
        'feat6_title' => 'Support Whenever You Face Issues',
        'feat6_desc'  => 'A dedicated technical support team ready to help you resolve any problem or error you encounter while using the platform',

        // ===== Feedback (static HTML) =====
        'contact_page_title'   => 'Share Your Feedback',
        'contact_page_sub'     => 'Your opinion matters! Help us improve the platform and develop it to better suit your needs.',
        'contact_info_email'   => 'Email',
        'contact_info_loc'     => 'Location',
        'contact_info_loc_val' => 'Suez University – Faculty of Science',
        'contact_info_reply'   => 'Response Time',
        'contact_info_reply_val' => 'Within 24 hours of receiving your feedback',
        'contact_info_support' => 'Technical Support',
        'contact_info_support_val' => 'A dedicated team always ready to help you',
        'contact_name_label'   => 'Name',
        'contact_name_ph'      => 'Enter your full name',
        'contact_name_err'     => 'Please enter your full name',
        'contact_code_label'   => 'University Code',
        'contact_code_ph'      => 'Enter your university code',
        'contact_code_err'     => 'Please enter your university code',
        'contact_email_label'  => 'Email',
        'contact_email_ph'     => 'Enter your email address',
        'contact_email_err'    => 'Please enter a valid email address',
        'contact_topic_label'  => 'Feedback Topic',
        'contact_topic_ui'     => 'Platform Interface',
        'contact_topic_content'=> 'Educational Content',
        'contact_topic_perf'   => 'Performance & Speed',
        'contact_topic_support'=> 'Technical Support',
        'contact_topic_suggest'=> 'General Suggestions',
        'contact_topic_other'  => 'Other',
        'contact_msg_label'    => 'Your Feedback / Suggestion',
        'contact_msg_ph'       => 'Write your feedback or suggestion here...',
        'contact_msg_err'      => 'Please write your feedback or suggestion',
        'contact_thanks_title' => 'Thank you!',
        'contact_thanks_msg'   => 'Your feedback has been sent successfully. We will take it into account when developing the platform.',
        'contact_close_btn'    => 'Close',

        // ===== Sidebar short brand =====
        'sidebar_brand_short'  => 'Smart Platform',

        // ===== Content type buttons =====
        'content_lectures' => 'Lectures',
        'content_tasks'    => 'Tasks',
        'content_assign'   => 'Assignments',
        'content_sections' => 'Sections',

        // ===== Section filter + upload button =====
        'section_all'        => 'All',
        'upload_btn_generic' => 'Upload File',

        // ===== Exam schedule =====
        'exam_sched_subtitle'  => 'Exam Dates',
        'exam_sched_upload'    => 'Upload Exam Schedule',
        'view_grade_label'     => 'View Grade:',
        'exam_sched_loading'   => 'Loading exam schedule...',
        'exam_sched_auto'      => 'Automatically determined based on your grade level',

        // ===== Online exams =====
        'online_exams_admin_title'  => 'Manage Online Exams',
        'online_exams_title'        => 'Online Exams',
        'online_exams_admin_sub'    => 'Upload exams and review student answers',
        'online_exams_sub'          => 'Take online exams and view your results',
        'create_exam_btn'           => '+ Create Exam',
        'exam_basic_data'           => '📝 Basic Exam Information',
        'exam_grade_label'          => 'Grade Level *',
        'exam_subject_label'        => 'Subject *',
        'exam_choose_subject'       => 'Select subject...',
        'exam_title_label'          => 'Exam Title *',
        'exam_title_ph'             => 'e.g., Statistics Exam - First Semester',
        'exam_desc_label'           => 'Description (Exam Type)',
        'exam_desc_ph'              => 'e.g., MCQ exam covering chapters 1-5 / Essay exam...',
        'exam_duration_label'       => 'Exam Duration (minutes) *',
        'exam_total_grade_label'    => 'Total Grade *',
        'exam_pass_grade_label'     => 'Passing Grade *',
        'exam_questions_title'      => '❓ Questions',
        'exam_add_question_btn'     => 'Add Question',
        'exam_upload_btn'           => 'Upload Exam',
        'exam_cancel_btn'           => 'Cancel',
        'exam_tab_list'             => 'Exams List',
        'exam_tab_submissions'      => 'Review Answers',
        'exam_tab_available'        => 'Available Exams',
        'exam_tab_results'          => 'My Results',
        'exam_loading'              => 'Loading exams...',

        // ===== Review panel =====
        'pending_sub'      => 'Files uploaded by students awaiting your approval',
        'pending_refresh'  => 'Refresh',
        'pending_loading'  => 'Loading...',

        // ===== Profile (static fallback text) =====
        'profile_static_sub'   => 'Your personal and academic information',
        'profile_static_dept'  => 'Math & Computer Science · Faculty of Science',
        'profile_section_label'=> 'Division',
        'profile_uni_label'    => 'University',
        'profile_uni_value'    => 'Suez University',

        // ===== Upload modal (extra fields) =====
        'modal_grade_label'      => 'Grade',
        'modal_section_label'    => 'Section Number',
        'modal_choose_file_label'=> 'Choose File',
        'modal_choose_file_text' => 'Click to choose a file from your device',
        'modal_choose_file_short'=> 'Click to choose a file',
        'modal_upload_btn'       => 'Upload File',
        'modal_cancel_btn'       => 'Cancel',

        // ===== Delete confirmation =====
        'delete_confirm_title' => 'Delete File',
        'delete_confirm_msg'   => 'Are you sure you want to permanently delete this file?<br>This action cannot be undone.',
        'delete_confirm_yes'   => 'Delete',
        'delete_confirm_no'    => 'Cancel',
        'select_placeholder'   => 'Select...',

        // ===== Exam Schedule (JS) =====
        'exam_sched_empty_title' => 'No Exam Schedule',
        'exam_sched_empty_sub'   => 'The exam schedule has not been uploaded yet',
        'exam_sched_card_type'   => 'Exam Schedule',
        'exam_sched_load_err'    => 'Error loading exam schedule',

        // ===== Pending review panel (JS) =====
        'pending_empty_title' => 'No Files Pending Review',
        'pending_empty_sub'   => 'All files have been reviewed',
        'pending_load_err'    => 'Error loading files',

        // ===== Exams list =====
        'exam_load_err'          => 'Error loading exams',
        'exam_none_for_grade'    => 'No exams available for this grade',
        'exam_none_available'    => 'No exams available at the moment',
        'exam_click'             => 'Click',
        'exam_click_to_add'      => 'to add a new exam',
        'exam_will_appear'       => 'Exams will appear here once made available by the admin',
        'exam_conn_error'        => 'Server connection error',
        'exam_status_active'     => 'Active ✅',
        'exam_status_inactive'   => 'Inactive ⛔',
        'exam_disable_btn'       => '⛔ Disable',
        'exam_enable_btn'        => '✅ Enable',
        'exam_status_banned'     => 'Banned 🚫',
        'exam_banned_btn'        => 'Banned from Exam',
        'exam_status_done'       => 'Completed ✅',
        'exam_submitted_btn'     => 'Submitted',
        'exam_status_available'  => 'Available 🟢',
        'exam_delete_confirm'    => 'Are you sure you want to delete this exam and all student data?',
        'exam_delete_err'        => 'Error deleting exam',
        'exam_conn_err_short'    => 'Connection error',
        'exam_generic_err'       => 'Error',

        // ===== Review submissions =====
        'submissions_loading'    => 'Loading answers...',
        'submissions_empty_title'=> 'No Submitted Exams',
        'submissions_empty_sub'  => 'Submissions will appear here once students submit their exams',
        'submissions_load_err'   => 'Error loading data',
        'submissions_cheat'      => '⚠️ Cheating Attempts',
        'submissions_notes'      => 'Notes (optional)',
        'submissions_reviewed'   => '✅ Reviewed',
        'submissions_enter_grade'=> 'Please enter a grade first',
        'submissions_save_err'   => 'Error saving',
        'submissions_answers_err'=> 'Error loading answers',
        'submissions_no_answer'  => 'No answer provided',
        'submissions_no_answer_warn' => '⚠️ No answer',

        // ===== My Results (student) =====
        'results_loading'      => 'Loading your results...',
        'results_empty_title'  => 'No Results Yet',
        'results_empty_sub'    => 'Exam results will appear here once reviewed by the admin',
        'results_pass'         => '✅ Passed',
        'results_fail'         => '❌ Failed',
        'results_pending'      => '⏳ Pending Review',

        // ===== Exam creation form (JS) =====
        'exam_form_loading_opt'  => 'Loading...',
        'exam_form_choose_subj'  => 'Select subject...',
        'exam_form_load_err_opt' => 'Error loading',
        'exam_form_grade_col'    => 'Grade',
        'exam_form_question_ph'  => 'Write the question here...',
        'exam_form_choice_a'     => 'Choice A',
        'exam_form_choice_b'     => 'Choice B',
        'exam_form_choice_c'     => 'Choice C',
        'exam_form_choice_d'     => 'Choice D',
        'exam_form_question_num' => 'Question',
        'exam_form_err_required' => '⚠️ Please fill in all required fields',
        'exam_form_err_qtext'    => '⚠️ Please fill in the text of all questions',
        'exam_form_err_mcq'      => '⚠️ At least choices A and B must be added for each MCQ question',
        'exam_form_err_min1'     => '⚠️ At least one question must be added',
        'exam_form_uploading'    => 'Uploading...',
        'exam_form_success'      => '✅ Exam uploaded successfully!',
        'exam_form_upload_err'   => 'Error uploading',
        'exam_form_conn_err'     => '⚠️ Server connection error',
        'file_subject_label'     => 'Subject',
        'file_type_label'        => 'Type',
        'exam_students_submitted'=> '📥 Students Submitted',
        'exam_student_unit'      => 'students',
        'exam_duration_icon'     => '⏱️ Duration',
        'exam_minute_unit'       => 'min',
        'exam_questions_icon'    => '❓ Questions',
        'exam_question_unit'     => 'questions',
        'exam_total_grade_icon'  => '📊 Total Grade',
        'exam_grade_unit'        => 'points',
        'exam_pass_icon'         => '✅ Passing Grade',
        'exam_start_btn'         => 'Start Exam',
        'exam_delete_icon_btn'   => '🗑️ Delete',
        'exam_cheat_prefix'      => '⚠️ Cheating Attempts',
        'exam_given_grade'       => '✅ Given Grade:',
        'exam_grade_from'        => 'Grade (out of',
        'exam_save_btn'          => '💾 Save',
        'exam_view_answers_btn'  => '🔍 View Answers',
        'exam_code_prefix'       => '🎓 Code:',
        'exam_enter_grade_first' => 'Please enter a grade first',
        'exam_cheat_log_title'   => '⚠️ Cheating Attempts Log',
        'exam_q_prefix'          => 'Q',
        'exam_back_to_list'      => 'Back to List',
        'exam_answers_of'        => 'Answers:',
        'exam_started_at'        => '⏱️ Started:',
        'exam_submitted_at_label'=> '✅ Submitted:',
        'exam_result_of'         => 'out of',
        'exam_type_mcq'          => 'Multiple Choice (MCQ)',
        'exam_type_essay'        => 'Essay',
        'exam_marks_ph'          => 'Marks',
        'exam_remove_q_btn'      => '✕ Remove',
        'exam_question_text_label' => 'Question Text *',
        'exam_correct_answer_label'=> 'Correct Answer *',
        'exam_letter_a' => 'A', 'exam_letter_b' => 'B', 'exam_letter_c' => 'C', 'exam_letter_d' => 'D',
        'sched_no_section_title' => 'Select a section number to view the schedule',
        'sched_no_section_sub'   => 'Your grade level is determined automatically from your account',
        'sched_empty_title'      => 'No Schedule for This Section',
        'sched_empty_sub'        => 'The schedule has not been uploaded yet',
        'sched_card_type'        => 'Class Schedule',
        'sched_load_err'         => 'Error loading schedule',

        // ===== Doctor Page =====
        'doctor_page_title'    => 'Doctor Dashboard - Smart Platform - Faculty of Science',
        'doctor_welcome'       => 'Welcome Dr.',
        'doc_content_lecture'    => 'Lectures',
        'doc_content_assignment' => 'Assignment',
        'doc_content_task'       => 'Tasks',
        'doc_content_section'    => 'Sections',
        'doc_load_subjects_err'  => 'Error loading subjects',
        'doc_load_files_err'     => 'Error loading files',
        'doc_delete_confirm'     => 'Are you sure you want to delete this file? This action cannot be undone.',
        'doc_delete_failed'      => 'Failed to delete the file',
        'doc_conn_error'         => 'Server connection error',
        'doc_choose_file_first'  => 'Please choose a file first',
        'doc_upload_generic_err' => 'An error occurred during upload',

        // ===== Reset Password =====
        'reset_page_title'   => 'Reset Password',
        'reset_step_of'      => 'Step %d of 3',

        // Step 1
        'reset_s1_title'     => 'Reset Your Password',
        'reset_s1_sub'       => 'Enter your details to verify your identity',
        'reset_s1_code_label'=> 'University Code',
        'reset_s1_code_ph'   => 'Enter your university code',
        'reset_s1_code_hint' => 'Use your official university code',
        'reset_s1_code_err'  => 'Please enter your university code',
        'reset_s1_verify_btn'=> 'Verify Identity',
        'reset_s1_remember'  => 'Remember your password?',
        'reset_s1_login_link'=> 'Login',

        // Step 2 (OTP)
        'reset_s2_title'     => 'Verification Code',
        'reset_s2_sub'       => 'Enter the OTP code sent to your email',
        'reset_s2_label'     => '6-digit verification code',
        'reset_s2_err'       => 'Please enter the 6-digit code',
        'reset_s2_no_code'   => "Didn't receive the code?",
        'reset_s2_resend'    => 'Resend',
        'reset_s2_verify_btn'=> 'Verify Code',
        'reset_s2_back_btn'  => 'Back to Previous Step',

        // Step 3
        'reset_s3_title'      => 'New Password',
        'reset_s3_sub'        => 'Enter a new, strong password for your account',
        'reset_s3_pass_label' => 'New Password',
        'reset_s3_pass_ph'    => 'Enter new password (min 6 characters)',
        'reset_s3_pass_err'   => 'Password must be at least 6 characters',
        'reset_s3_confirm_label' => 'Confirm New Password',
        'reset_s3_confirm_ph' => 'Re-enter your new password',
        'reset_s3_confirm_err_empty' => 'Please confirm your password',
        'reset_s3_confirm_err_mismatch' => 'Passwords do not match',
        'reset_s3_submit_btn' => 'Reset Password',

        // Success
        'reset_success_title' => 'Success! 🎉',
        'reset_success_msg'   => 'Your password has been reset successfully.<br>You can now log in with your new password.',
        'reset_success_btn'   => 'Go to Login',

        // Right panel
        'reset_panel_title'   => 'Recover Your Account',
        'reset_panel_desc'    => 'Follow the simple steps to reset your password and return to your Smart Platform for the Faculty of Science, Math & CS Division',
        'reset_prog1'         => 'Verify Identity',
        'reset_prog2'         => 'Verification Code',
        'reset_prog3'         => 'New Password',
        'reset_feat1'         => 'High security to protect your account',
        'reset_feat2'         => 'A verification code sent instantly to your email',
        'reset_feat3'         => 'A fast and secure 3-step process',

        // JS messages
        'reset_toast_verifying'   => 'Verifying...',
        'reset_toast_verified'    => 'Identity verified ✓ Redirecting...',
        'reset_toast_wrong_code'  => 'Incorrect university code',
        'reset_toast_code_notfound'=> 'University code not found',
        'reset_toast_conn_err'    => 'Server connection error',
        'reset_toast_otp_verified'=> 'Code verified ✓ Redirecting...',
        'reset_toast_otp_resent'  => 'Verification code resent',
        'reset_toast_saving'      => 'Saving...',
        'reset_toast_success'     => 'Password reset successfully 🎉',
        'reset_toast_generic_err' => 'An error occurred, please try again',
        'reset_show'  => 'Show',
        'reset_hide'  => 'Hide',
    ],
];

/**
 * إرجاع النص المترجم حسب اللغة الحالية
 * لو المفتاح مش موجود، بيرجّع المفتاح نفسه (عشان نلاحظ أي نص ناقص بسهولة)
 */
function t(string $key): string {
    global $TRANSLATIONS, $currentLang;
    return $TRANSLATIONS[$currentLang][$key] ?? $key;
}
